<?php

/**
 * @file
 * Module's main file. Provides work with different IMDB APIs.
 */

/**
 * Implements hook_cron().
 */
function imdb_cron() {
  /** @var \Drupal\imdb\IMDbQueueManager $imdb_queue_manager */
  $imdb_queue_manager = Drupal::service('plugin.manager.imdb_queue');
  /** @var \Drupal\imdb\Plugin\IMDbQueue\TMDbQueue $tmdb_queue */
  $tmdb_queue = $imdb_queue_manager->createInstance('tmdb_queue');

  if (!$tmdb_queue->isEmpty()) {
    // Get results from TMDb queue and set them to "Saver" queue.
    /** @var \Drupal\imdb\IMDbQueueItem $item */
    foreach ($tmdb_queue->getResults() as $item) {
      /**
       * @see \Drupal\imdb_saver\Plugin\QueueWorker\TMDbSaver
       */
      Drupal::queue('tmdb_result_saver')->createItem([
        'item' => $item,
      ]);
    }
  }


  //  // Додати настройку "раз в стільки-то днів обновляти рейтинги".
  //  if (!$OMDbQueue->numberOfItems()) {
  //    // 1. Знайти всі ноди, в яких дата останнього обновлення рейтингу старіша,
  //    // ніж в настройці вище.
  //    // 2. Додати Node IDs в чергу OMDb.
  //  }
  //  else {
  //    // 1. Просто робити запити до OMDb API і апдейтити філд рейтинга ноди.
  //  }
}

/**
 * Implements hook_toolbar_alter().
 *
 * @param $items
 *   Associative array of toolbar menu definitions returned from hook_toolbar().
 */
function imdb_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'imdb/imdb.menu';
}
