<?php

/**
 * @file
 * Module's main file. Provides work with different IMDB APIs.
 */

use Drupal\imdb\IMDbQueueItemRequestType;

/**
 * Implements hook_cron().
 *
 * {@inheritDoc}
 */
function imdb_cron() {
  /** @var \Drupal\imdb\IMDbQueueManager $imdb_queue_manager */
  $imdb_queue_manager = Drupal::service('plugin.manager.imdb_queue');
  /** @var \Drupal\imdb\Plugin\IMDbQueue\TMDbQueue $tmdb_queue */
  $tmdb_queue = $imdb_queue_manager->createInstance('tmdb_queue');

  if (!$tmdb_queue->isEmpty()) {
    // Get results from TMDb service.
    $tmdb_results = $tmdb_queue->getResults();

    /** @var \Drupal\imdb\IMDbQueueItem $result */
    foreach ($tmdb_results as $result) {
      switch ($result->getRequestType()) {
        case IMDbQueueItemRequestType::FIND:
          // Nothing to save for this type.
          break;

        case IMDbQueueItemRequestType::MOVIE:
          /**
           * @see \Drupal\imdb_saver\Plugin\QueueWorker\TMDbSaver
           * @see \Drupal\imdb_saver\Plugin\IMDbSaver\MovieSaver
           */
          Drupal::queue('tmdb_result_saver')->createItem([
            'plugin_id' => 'movie_saver',
            'item' => $result,
          ]);
          break;

        case IMDbQueueItemRequestType::TV:
          /**
           * @see \Drupal\imdb_saver\Plugin\QueueWorker\TMDbSaver
           * @see \Drupal\imdb_saver\Plugin\IMDbSaver\TvSaver
           */
          Drupal::queue('tmdb_result_saver')->createItem([
            'plugin_id' => 'tv_saver',
            'item' => $result,
          ]);
          break;

        default:
          $message = t("ResourceSaver try to save node with undefined type %type.", [
            '%type' => $result->getRequestType(),
          ]);
          Drupal::messenger()->addError($message);
          Drupal::logger('imdb_cron:' . __LINE__)->error($message);
          return;
      }
    }
  }


  //  // Додати настройку "раз в стільки-то днів обновляти рейтинги".
  //  if (!$OMDbQueue->numberOfItems()) {
  //    // 1. Знайти всі ноди, в яких дата останнього обновлення рейтингу старіша,
  //    // ніж в настройці вище.
  //    // 2. Додати Node IDs в чергу OMDb.
  //  }
  //  else {
  //    // 1. Просто робити запити до OMDb API і апдейтити філд рейтинга ноди.
  //  }
}

/**
 * Implements hook_toolbar_alter().
 *
 * {@inheritDoc}
 */
function imdb_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'imdb/imdb.menu';
}
