<?php

namespace PHPSTORM_META {

  override(
    \Drupal::service(0),
    map([
      'service_container' => '\Symfony\Component\DependencyInjection\ContainerInterface',
      'drush.console.services' => '\Drush\Command\ServiceCommandlist',
      'drush.command.services' => '\Drush\Command\ServiceCommandlist',
      'drush.command_info_alterer.services' => '\Drush\Command\ServiceCommandlist',
      'drush.generator.services' => '\Drush\Command\ServiceCommandlist',
      'kernel' => '\Symfony\Component\HttpKernel\KernelInterface',
      'cache_context.ip' => '\Drupal\Core\Cache\Context\IpCacheContext',
      'cache_context.headers' => '\Drupal\Core\Cache\Context\HeadersCacheContext',
      'cache_context.cookies' => '\Drupal\Core\Cache\Context\CookiesCacheContext',
      'cache_context.session' => '\Drupal\Core\Cache\Context\SessionCacheContext',
      'cache_context.session.exists' => '\Drupal\Core\Cache\Context\SessionExistsCacheContext',
      'cache_context.request_format' => '\Drupal\Core\Cache\Context\RequestFormatCacheContext',
      'cache_context.url' => '\Drupal\Core\Cache\Context\UrlCacheContext',
      'cache_context.url.site' => '\Drupal\Core\Cache\Context\SiteCacheContext',
      'cache_context.url.path' => '\Drupal\Core\Cache\Context\PathCacheContext',
      'cache_context.url.path.parent' => '\Drupal\Core\Cache\Context\PathParentCacheContext',
      'cache_context.url.path.is_front' => '\Drupal\Core\Cache\Context\IsFrontPathCacheContext',
      'cache_context.url.query_args' => '\Drupal\Core\Cache\Context\QueryArgsCacheContext',
      'cache_context.url.query_args.pagers' => '\Drupal\Core\Cache\Context\PagersCacheContext',
      'cache_context.route' => '\Drupal\Core\Cache\Context\RouteCacheContext',
      'cache_context.route.name' => '\Drupal\Core\Cache\Context\RouteNameCacheContext',
      'cache_context.route.menu_active_trails' => '\Drupal\Core\Cache\Context\MenuActiveTrailsCacheContext',
      'cache_context.user' => '\Drupal\Core\Cache\Context\UserCacheContext',
      'cache_context.user.permissions' => '\Drupal\Core\Cache\Context\AccountPermissionsCacheContext',
      'cache_context.user.roles' => '\Drupal\Core\Cache\Context\UserRolesCacheContext',
      'cache_context.user.is_super_user' => '\Drupal\Core\Cache\Context\IsSuperUserCacheContext',
      'cache_context.languages' => '\Drupal\Core\Cache\Context\LanguagesCacheContext',
      'cache_context.theme' => '\Drupal\Core\Cache\Context\ThemeCacheContext',
      'cache_context.timezone' => '\Drupal\Core\Cache\Context\TimeZoneCacheContext',
      'cache_factory' => '\Drupal\Core\Cache\CacheFactory',
      'cache_contexts_manager' => '\Drupal\Core\Cache\Context\CacheContextsManager',
      'cache_tags.invalidator' => '\Drupal\Core\Cache\CacheTagsInvalidator',
      'cache_tags.invalidator.checksum' => '\Drupal\Core\Cache\DatabaseCacheTagsChecksum',
      'cache.backend.chainedfast' => '\Drupal\Core\Cache\ChainedFastBackendFactory',
      'cache.backend.database' => '\Drupal\Core\Cache\DatabaseBackendFactory',
      'cache.backend.apcu' => '\Drupal\Core\Cache\ApcuBackendFactory',
      'cache.backend.php' => '\Drupal\Core\Cache\PhpBackendFactory',
      'cache.backend.memory' => '\Drupal\Core\Cache\MemoryBackendFactory',
      'cache.static' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.bootstrap' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.config' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.default' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.entity' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.menu' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.render' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.data' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache.discovery' => '\Drupal\Core\Cache\CacheBackendInterface',
      'cache_router_rebuild_subscriber' => '\Drupal\Core\EventSubscriber\CacheRouterRebuildSubscriber',
      'page_cache_request_policy' => '\Drupal\Core\PageCache\DefaultRequestPolicy',
      'page_cache_response_policy' => '\Drupal\Core\ProxyClass\PageCache\ChainResponsePolicy',
      'page_cache_kill_switch' => '\Drupal\Core\PageCache\ResponsePolicy\KillSwitch',
      'config.manager' => '\Drupal\Core\Config\ConfigManager',
      'config.factory' => '\Drupal\Core\Config\ConfigFactory',
      'config.importer_subscriber' => '\Drupal\Core\Config\Importer\FinalMissingContentSubscriber',
      'config.installer' => '\Drupal\Core\ProxyClass\Config\ConfigInstaller',
      'config.storage' => '\Drupal\Core\Config\CachedStorage',
      'config.import_transformer' => '\Drupal\Core\Config\ImportStorageTransformer',
      'config.storage.export' => '\Drupal\Core\Config\ManagedStorage',
      'config.storage.staging' => '\Drupal\Core\Config\FileStorage',
      'config.storage.snapshot' => '\Drupal\Core\Config\DatabaseStorage',
      'config.storage.schema' => '\Drupal\Core\Config\ExtensionInstallStorage',
      'config.typed' => '\Drupal\Core\Config\TypedConfigManager',
      'context.handler' => '\Drupal\Core\Plugin\Context\ContextHandler',
      'context.repository' => '\Drupal\Core\Plugin\Context\LazyContextRepository',
      'cron' => '\Drupal\alter\ProxyClass\CronAlter',
      'diff.formatter' => '\Drupal\Core\Diff\DiffFormatter',
      'database' => '\Drupal\Core\Database\Connection',
      'database.replica' => '\Drupal\Core\Database\Connection',
      'database.replica_kill_switch' => '\Drupal\Core\Database\ReplicaKillSwitch',
      'datetime.time' => '\Drupal\Component\Datetime\Time',
      'file_system' => '\Drupal\Core\File\FileSystem',
      'form_builder' => '\Drupal\Core\Form\FormBuilder',
      'form_validator' => '\Drupal\Core\Form\FormValidator',
      'form_submitter' => '\Drupal\Core\Form\FormSubmitter',
      'form_error_handler' => '\Drupal\Core\Form\FormErrorHandler',
      'keyvalue' => '\Drupal\Core\KeyValueStore\KeyValueFactory',
      'keyvalue.database' => '\Drupal\Core\KeyValueStore\KeyValueDatabaseFactory',
      'keyvalue.expirable' => '\Drupal\Core\KeyValueStore\KeyValueExpirableFactory',
      'keyvalue.expirable.database' => '\Drupal\Core\KeyValueStore\KeyValueDatabaseExpirableFactory',
      'logger.factory' => '\Drupal\Core\Logger\LoggerChannelFactory',
      'logger.channel.default' => '\Drupal\Core\Logger\LoggerChannel',
      'logger.channel.php' => '\Drupal\Core\Logger\LoggerChannel',
      'logger.channel.image' => '\Drupal\Core\Logger\LoggerChannel',
      'logger.channel.cron' => '\Drupal\Core\Logger\LoggerChannel',
      'logger.channel.file' => '\Drupal\Core\Logger\LoggerChannel',
      'logger.channel.form' => '\Drupal\Core\Logger\LoggerChannel',
      'logger.channel.security' => '\Drupal\Core\Logger\LoggerChannel',
      'logger.log_message_parser' => '\Drupal\Core\Logger\LogMessageParser',
      'serialization.json' => '\Drupal\Component\Serialization\Json',
      'serialization.phpserialize' => '\Drupal\Component\Serialization\PhpSerialize',
      'serialization.yaml' => '\Drupal\Component\Serialization\Yaml',
      'settings' => '\Drupal\Core\Site\Settings',
      'state' => '\Drupal\Core\State\State',
      'queue' => '\Drupal\Core\Queue\QueueFactory',
      'queue.database' => '\Drupal\Core\Queue\QueueDatabaseFactory',
      'path.alias_manager' => '\Drupal\Core\Path\AliasManager',
      'path.current' => '\Drupal\Core\Path\CurrentPathStack',
      'http_client' => '\GuzzleHttp\Client',
      'http_client_factory' => '\Drupal\Core\Http\ClientFactory',
      'plugin.manager.link_relation_type' => '\Drupal\Core\Http\LinkRelationTypeManager',
      'theme.negotiator' => '\Drupal\Core\Theme\ThemeNegotiator',
      'theme.negotiator.default' => '\Drupal\Core\Theme\DefaultNegotiator',
      'theme.negotiator.ajax_base_page' => '\Drupal\Core\Theme\AjaxBasePageNegotiator',
      'container.namespaces' => '\ArrayObject',
      'module_handler' => '\Drupal\Core\Extension\ModuleHandler',
      'module_installer' => '\Drupal\Core\ProxyClass\Extension\ModuleInstaller',
      'extension.list.module' => '\Drupal\Core\Extension\ModuleExtensionList',
      'extension.list.profile' => '\Drupal\Core\Extension\ProfileExtensionList',
      'extension.list.theme' => '\Drupal\Core\Extension\ThemeExtensionList',
      'extension.list.theme_engine' => '\Drupal\Core\Extension\ThemeEngineExtensionList',
      'content_uninstall_validator' => '\Drupal\Core\ProxyClass\Entity\ContentUninstallValidator',
      'required_module_uninstall_validator' => '\Drupal\Core\ProxyClass\Extension\RequiredModuleUninstallValidator',
      'theme_handler' => '\Drupal\Core\Extension\ThemeHandler',
      'theme_installer' => '\Drupal\Core\Extension\ThemeInstaller',
      'entity.manager' => '\Drupal\Core\Entity\EntityManager',
      'entity.memory_cache' => '\Drupal\Core\Cache\MemoryCache\MemoryCache',
      'entity_type.manager' => '\Drupal\Core\Entity\EntityTypeManager',
      'entity_type.repository' => '\Drupal\Core\Entity\EntityTypeRepository',
      'entity_type.bundle.info' => '\Drupal\Core\Entity\EntityTypeBundleInfo',
      'entity.repository' => '\Drupal\Core\Entity\EntityRepository',
      'entity_display.repository' => '\Drupal\Core\Entity\EntityDisplayRepository',
      'entity_field.manager' => '\Drupal\Core\Entity\EntityFieldManager',
      'entity_type.listener' => '\Drupal\Core\Entity\EntityTypeListener',
      'entity_bundle.listener' => '\Drupal\Core\Entity\EntityBundleListener',
      'entity_route_subscriber' => '\Drupal\Core\EventSubscriber\EntityRouteProviderSubscriber',
      'entity.definition_update_manager' => '\Drupal\Core\Entity\EntityDefinitionUpdateManager',
      'entity.last_installed_schema.repository' => '\Drupal\Core\Entity\EntityLastInstalledSchemaRepository',
      'entity_field.deleted_fields_repository' => '\Drupal\Core\Field\DeletedFieldsRepository',
      'field_storage_definition.listener' => '\Drupal\Core\Field\FieldStorageDefinitionListener',
      'field_definition.listener' => '\Drupal\Core\Field\FieldDefinitionListener',
      'entity.form_builder' => '\Drupal\Core\Entity\EntityFormBuilder',
      'entity.bundle_config_import_validator' => '\Drupal\Core\Entity\Event\BundleConfigImportValidate',
      'entity.autocomplete_matcher' => '\Drupal\Core\Entity\EntityAutocompleteMatcher',
      'plugin_form.factory' => '\Drupal\Core\Plugin\PluginFormFactory',
      'plugin.manager.entity_reference_selection' => '\Drupal\Core\Entity\EntityReferenceSelection\SelectionPluginManager',
      'plugin.manager.block' => '\Drupal\Core\Block\BlockManager',
      'plugin.manager.field.field_type' => '\Drupal\Core\Field\FieldTypePluginManager',
      'plugin.manager.field.widget' => '\Drupal\Core\Field\WidgetPluginManager',
      'plugin.manager.field.formatter' => '\Drupal\Core\Field\FormatterPluginManager',
      'plugin.manager.archiver' => '\Drupal\Core\Archiver\ArchiverManager',
      'plugin.manager.action' => '\Drupal\Core\Action\ActionManager',
      'plugin.manager.menu.link' => '\Drupal\Core\Menu\MenuLinkManager',
      'menu.link_tree' => '\Drupal\Core\Menu\MenuLinkTree',
      'menu.default_tree_manipulators' => '\Drupal\Core\Menu\DefaultMenuLinkTreeManipulators',
      'menu.active_trail' => '\Drupal\Core\Menu\MenuActiveTrail',
      'menu.parent_form_selector' => '\Drupal\Core\Menu\MenuParentFormSelector',
      'plugin.manager.menu.local_action' => '\Drupal\Core\Menu\LocalActionManager',
      'plugin.manager.menu.local_task' => '\Drupal\Core\Menu\LocalTaskManager',
      'plugin.manager.menu.contextual_link' => '\Drupal\Core\Menu\ContextualLinkManager',
      'plugin.manager.display_variant' => '\Drupal\Core\Display\VariantManager',
      'plugin.manager.queue_worker' => '\Drupal\Core\Queue\QueueWorkerManager',
      'plugin.cache_clearer' => '\Drupal\Core\ProxyClass\Plugin\CachedDiscoveryClearer',
      'paramconverter.menu_link' => '\Drupal\Core\ProxyClass\ParamConverter\MenuLinkPluginConverter',
      'menu_link.static.overrides' => '\Drupal\Core\Menu\StaticMenuLinkOverrides',
      'request_stack' => '\Symfony\Component\HttpFoundation\RequestStack',
      'current_route_match' => '\Drupal\Core\Routing\CurrentRouteMatch',
      'event_dispatcher' => '\Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher',
      'app.root' => '\SplString',
      'site.path' => '\SplString',
      'controller_resolver' => '\Drupal\Core\Controller\ControllerResolver',
      'class_resolver' => '\Drupal\Core\DependencyInjection\ClassResolver',
      'title_resolver' => '\Drupal\Core\Controller\TitleResolver',
      'http_kernel' => '\Stack\StackedHttpKernel',
      'http_kernel.basic' => '\Symfony\Component\HttpKernel\HttpKernel',
      'http_kernel.controller.argument_resolver' => '\Symfony\Component\HttpKernel\Controller\ArgumentResolver',
      'http_middleware.negotiation' => '\Drupal\Core\StackMiddleware\NegotiationMiddleware',
      'http_middleware.reverse_proxy' => '\Drupal\Core\StackMiddleware\ReverseProxyMiddleware',
      'http_middleware.kernel_pre_handle' => '\Drupal\Core\StackMiddleware\KernelPreHandle',
      'http_middleware.session' => '\Drupal\Core\StackMiddleware\Session',
      'psr7.http_foundation_factory' => '\Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory',
      'psr7.http_message_factory' => '\Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory',
      'language_manager' => '\Drupal\language\ConfigurableLanguageManager',
      'language.current_language_context' => '\Drupal\Core\Language\ContextProvider\CurrentLanguageContext',
      'language.default' => '\Drupal\Core\Language\LanguageDefault',
      'string_translator.custom_strings' => '\Drupal\Core\StringTranslation\Translator\CustomStrings',
      'string_translation' => '\Drupal\Core\StringTranslation\TranslationManager',
      'typed_data_manager' => '\Drupal\Core\TypedData\TypedDataManager',
      'validation.constraint' => '\Drupal\Core\Validation\ConstraintManager',
      'lock' => '\Drupal\Core\ProxyClass\Lock\DatabaseLockBackend',
      'lock.persistent' => '\Drupal\Core\ProxyClass\Lock\PersistentDatabaseLockBackend',
      'router.request_context' => '\Drupal\Core\Routing\RequestContext',
      'router.admin_context' => '\Drupal\Core\Routing\AdminContext',
      'router.route_provider' => '\Drupal\Core\Routing\RouteProvider',
      'router.route_provider.lazy_builder' => '\Drupal\Core\Routing\RouteProviderLazyBuilder',
      'router.route_preloader' => '\Drupal\Core\Routing\RoutePreloader',
      'router.matcher.final_matcher' => '\Drupal\Core\Routing\UrlMatcher',
      'router.matcher' => '\Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher',
      'url_generator' => '\Drupal\Core\Render\MetadataBubblingUrlGenerator',
      'redirect.destination' => '\Drupal\Core\Routing\RedirectDestination',
      'unrouted_url_assembler' => '\Drupal\Core\Utility\UnroutedUrlAssembler',
      'link_generator' => '\Drupal\Core\Utility\LinkGenerator',
      'router' => '\Drupal\Core\Routing\AccessAwareRouter',
      'router.dynamic' => '\Symfony\Cmf\Component\Routing\DynamicRouter',
      'router.no_access_checks' => '\Drupal\Core\Routing\Router',
      'router.path_roots_subscriber' => '\Drupal\Core\EventSubscriber\PathRootsSubscriber',
      'entity.query' => '\Drupal\Core\Entity\Query\QueryFactory',
      'entity.query.config' => '\Drupal\Core\Config\Entity\Query\QueryFactory',
      'entity.query.sql' => '\Drupal\Core\Entity\Query\Sql\QueryFactory',
      'pgsql.entity.query.sql' => '\Drupal\Core\Entity\Query\Sql\pgsql\QueryFactory',
      'entity.query.null' => '\Drupal\Core\Entity\Query\Null\QueryFactory',
      'entity.query.keyvalue' => '\Drupal\Core\Entity\KeyValueStore\Query\QueryFactory',
      'router.dumper' => '\Drupal\Core\ProxyClass\Routing\MatcherDumper',
      'router.builder' => '\Drupal\Core\ProxyClass\Routing\RouteBuilder',
      'menu.rebuild_subscriber' => '\Drupal\Core\EventSubscriber\MenuRouterRebuildSubscriber',
      'path.alias_storage' => '\Drupal\Core\Path\AliasStorage',
      'path.matcher' => '\Drupal\Core\Path\PathMatcher',
      'path.validator' => '\Drupal\Core\Path\PathValidator',
      'password' => '\Drupal\Core\Password\PhpassHashedPassword',
      'request_format_route_filter' => '\Drupal\Core\Routing\RequestFormatRouteFilter',
      'method_filter' => '\Drupal\Core\Routing\MethodFilter',
      'content_type_header_matcher' => '\Drupal\Core\Routing\ContentTypeHeaderMatcher',
      'paramconverter_manager' => '\Drupal\Core\ParamConverter\ParamConverterManager',
      'paramconverter_subscriber' => '\Drupal\Core\EventSubscriber\ParamConverterSubscriber',
      'paramconverter.entity' => '\Drupal\Core\ParamConverter\EntityConverter',
      'paramconverter.entity_revision' => '\Drupal\Core\ParamConverter\EntityRevisionParamConverter',
      'paramconverter.configentity_admin' => '\Drupal\Core\ProxyClass\ParamConverter\AdminPathConfigEntityConverter',
      'route_subscriber.module' => '\Drupal\Core\EventSubscriber\ModuleRouteSubscriber',
      'resolver_manager.entity' => '\Drupal\Core\Entity\EntityResolverManager',
      'route_subscriber.entity' => '\Drupal\Core\EventSubscriber\EntityRouteAlterSubscriber',
      'ajax_response.subscriber' => '\Drupal\Core\EventSubscriber\AjaxResponseSubscriber',
      'form_ajax_subscriber' => '\Drupal\Core\Form\EventSubscriber\FormAjaxSubscriber',
      'route_enhancer.param_conversion' => '\Drupal\Core\Routing\Enhancer\ParamConversionEnhancer',
      'route_enhancer.form' => '\Drupal\Core\Routing\Enhancer\FormRouteEnhancer',
      'route_enhancer.entity' => '\Drupal\Core\Entity\Enhancer\EntityRouteEnhancer',
      'route_enhancer.entity_revision' => '\Drupal\Core\Routing\Enhancer\EntityRevisionRouteEnhancer',
      'route_special_attributes_subscriber' => '\Drupal\Core\EventSubscriber\SpecialAttributesRouteSubscriber',
      'route_http_method_subscriber' => '\Drupal\Core\EventSubscriber\RouteMethodSubscriber',
      'psr_response_view_subscriber' => '\Drupal\Core\EventSubscriber\PsrResponseSubscriber',
      'main_content_view_subscriber' => '\Drupal\Core\EventSubscriber\MainContentViewSubscriber',
      'renderer_non_html' => '\Drupal\Core\EventSubscriber\RenderArrayNonHtmlSubscriber',
      'main_content_renderer.html' => '\Drupal\Core\Render\MainContent\HtmlRenderer',
      'main_content_renderer.ajax' => '\Drupal\Core\Render\MainContent\AjaxRenderer',
      'main_content_renderer.dialog' => '\Drupal\Core\Render\MainContent\DialogRenderer',
      'main_content_renderer.off_canvas' => '\Drupal\Core\Render\MainContent\OffCanvasRenderer',
      'main_content_renderer.off_canvas_top' => '\Drupal\Core\Render\MainContent\OffCanvasRenderer',
      'main_content_renderer.modal' => '\Drupal\Core\Render\MainContent\ModalRenderer',
      'controller.form' => '\Drupal\Core\Controller\HtmlFormController',
      'controller.entity_form' => '\Drupal\Core\Entity\HtmlEntityFormController',
      'form_ajax_response_builder' => '\Drupal\Core\Form\FormAjaxResponseBuilder',
      'router_listener' => '\Symfony\Component\HttpKernel\EventListener\RouterListener',
      'options_request_listener' => '\Drupal\Core\EventSubscriber\OptionsRequestSubscriber',
      'bare_html_page_renderer' => '\Drupal\Core\ProxyClass\Render\BareHtmlPageRenderer',
      'private_key' => '\Drupal\Core\PrivateKey',
      'csrf_token' => '\Drupal\Core\Access\CsrfTokenGenerator',
      'access_arguments_resolver_factory' => '\Drupal\Core\Access\AccessArgumentsResolverFactory',
      'access_manager' => '\Drupal\Core\Access\AccessManager',
      'access_check.default' => '\Drupal\Core\Access\DefaultAccessCheck',
      'access_check.entity' => '\Drupal\Core\Entity\EntityAccessCheck',
      'access_check.entity_create' => '\Drupal\Core\Entity\EntityCreateAccessCheck',
      'access_check.entity_create_any' => '\Drupal\Core\Entity\EntityCreateAnyAccessCheck',
      'access_check.entity_delete_multiple' => '\Drupal\Core\Entity\EntityDeleteMultipleAccessCheck',
      'access_check.theme' => '\Drupal\Core\Theme\ThemeAccessCheck',
      'access_check.custom' => '\Drupal\Core\Access\CustomAccessCheck',
      'access_check.csrf' => '\Drupal\Core\Access\CsrfAccessCheck',
      'access_check.header.csrf' => '\Drupal\Core\Access\CsrfRequestHeaderAccessCheck',
      'maintenance_mode' => '\Drupal\Core\Site\MaintenanceMode',
      'maintenance_mode_subscriber' => '\Drupal\Core\EventSubscriber\MaintenanceModeSubscriber',
      'path_subscriber' => '\Drupal\Core\EventSubscriber\PathSubscriber',
      'route_access_response_subscriber' => '\Drupal\Core\EventSubscriber\RouteAccessResponseSubscriber',
      'client_error_response_subscriber' => '\Drupal\Core\EventSubscriber\ClientErrorResponseSubscriber',
      'anonymous_user_response_subscriber' => '\Drupal\Core\EventSubscriber\AnonymousUserResponseSubscriber',
      'ajax_response.attachments_processor' => '\Drupal\Core\Ajax\AjaxResponseAttachmentsProcessor',
      'html_response.subscriber' => '\Drupal\Core\EventSubscriber\HtmlResponseSubscriber',
      'finish_response_subscriber' => '\Drupal\Core\EventSubscriber\FinishResponseSubscriber',
      'response_generator_subscriber' => '\Drupal\Core\EventSubscriber\ResponseGeneratorSubscriber',
      'redirect_response_subscriber' => '\Drupal\Core\EventSubscriber\RedirectResponseSubscriber',
      'redirect_leading_slashes_subscriber' => '\Drupal\Core\EventSubscriber\RedirectLeadingSlashesSubscriber',
      'request_close_subscriber' => '\Drupal\Core\EventSubscriber\RequestCloseSubscriber',
      'config_import_subscriber' => '\Drupal\Core\EventSubscriber\ConfigImportSubscriber',
      'config_snapshot_subscriber' => '\Drupal\Core\EventSubscriber\ConfigSnapshotSubscriber',
      'config_exclude_modules_subscriber' => '\Drupal\Core\EventSubscriber\ExcludedModulesEventSubscriber',
      'exception.needs_installer' => '\Drupal\Core\EventSubscriber\ExceptionDetectNeedsInstallSubscriber',
      'exception.default_json' => '\Drupal\Core\EventSubscriber\ExceptionJsonSubscriber',
      'exception.default_html' => '\Drupal\Core\EventSubscriber\DefaultExceptionHtmlSubscriber',
      'exception.final' => '\Drupal\Core\EventSubscriber\FinalExceptionSubscriber',
      'exception.logger' => '\Drupal\Core\EventSubscriber\ExceptionLoggingSubscriber',
      'exception.custom_page_html' => '\Drupal\Core\EventSubscriber\CustomPageExceptionHtmlSubscriber',
      'exception.fast_404_html' => '\Drupal\Core\EventSubscriber\Fast404ExceptionHtmlSubscriber',
      'exception.test_site' => '\Drupal\Core\EventSubscriber\ExceptionTestSiteSubscriber',
      'exception.enforced_form_response' => '\Drupal\Core\EventSubscriber\EnforcedFormResponseSubscriber',
      'route_processor_manager' => '\Drupal\Core\RouteProcessor\RouteProcessorManager',
      'path_processor_manager' => '\Drupal\Core\PathProcessor\PathProcessorManager',
      'path_processor_decode' => '\Drupal\Core\PathProcessor\PathProcessorDecode',
      'path_processor_front' => '\Drupal\Core\PathProcessor\PathProcessorFront',
      'route_processor_current' => '\Drupal\Core\RouteProcessor\RouteProcessorCurrent',
      'path_processor_alias' => '\Drupal\Core\PathProcessor\PathProcessorAlias',
      'route_processor_csrf' => '\Drupal\Core\Access\RouteProcessorCsrf',
      'transliteration' => '\Drupal\Core\Transliteration\PhpTransliteration',
      'flood' => '\Drupal\Core\Flood\DatabaseBackend',
      'plugin.manager.mail' => '\Drupal\Core\Mail\MailManager',
      'plugin.manager.condition' => '\Drupal\Core\Condition\ConditionManager',
      'plugin.manager.element_info' => '\Drupal\Core\Render\ElementInfoManager',
      'stream_wrapper_manager' => '\Drupal\Core\StreamWrapper\StreamWrapperManager',
      'stream_wrapper.public' => '\Drupal\Core\StreamWrapper\PublicStream',
      'stream_wrapper.temporary' => '\Drupal\Core\StreamWrapper\TemporaryStream',
      'kernel_destruct_subscriber' => '\Drupal\Core\EventSubscriber\KernelDestructionSubscriber',
      'image.toolkit.manager' => '\Drupal\Core\ImageToolkit\ImageToolkitManager',
      'image.toolkit.operation.manager' => '\Drupal\Core\ImageToolkit\ImageToolkitOperationManager',
      'image.factory' => '\Drupal\Core\Image\ImageFactory',
      'breadcrumb' => '\Drupal\Core\Breadcrumb\BreadcrumbManager',
      'token' => '\Drupal\Core\Utility\Token',
      'batch.storage' => '\Drupal\Core\ProxyClass\Batch\BatchStorage',
      'country_manager' => '\Drupal\Core\Locale\CountryManager',
      'date.formatter' => '\Drupal\Core\Datetime\DateFormatter',
      'feed.bridge.reader' => '\Drupal\Component\Bridge\ZfExtensionManagerSfContainer',
      'feed.bridge.writer' => '\Drupal\Component\Bridge\ZfExtensionManagerSfContainer',
      'feed.reader.dublincoreentry' => '\Zend\Feed\Reader\Extension\DublinCore\Entry',
      'feed.reader.dublincorefeed' => '\Zend\Feed\Reader\Extension\DublinCore\Feed',
      'feed.reader.contententry' => '\Zend\Feed\Reader\Extension\Content\Entry',
      'feed.reader.atomentry' => '\Zend\Feed\Reader\Extension\Atom\Entry',
      'feed.reader.atomfeed' => '\Zend\Feed\Reader\Extension\Atom\Feed',
      'feed.reader.slashentry' => '\Zend\Feed\Reader\Extension\Slash\Entry',
      'feed.reader.wellformedwebentry' => '\Zend\Feed\Reader\Extension\WellFormedWeb\Entry',
      'feed.reader.threadentry' => '\Zend\Feed\Reader\Extension\Thread\Entry',
      'feed.reader.podcastentry' => '\Zend\Feed\Reader\Extension\Podcast\Entry',
      'feed.reader.podcastfeed' => '\Zend\Feed\Reader\Extension\Podcast\Feed',
      'feed.writer.atomrendererfeed' => '\Zend\Feed\Writer\Extension\Atom\Renderer\Feed',
      'feed.writer.contentrendererentry' => '\Zend\Feed\Writer\Extension\Content\Renderer\Entry',
      'feed.writer.dublincorerendererentry' => '\Zend\Feed\Writer\Extension\DublinCore\Renderer\Entry',
      'feed.writer.dublincorerendererfeed' => '\Zend\Feed\Writer\Extension\DublinCore\Renderer\Feed',
      'feed.writer.itunesentry' => '\Zend\Feed\Writer\Extension\ITunes\Entry',
      'feed.writer.itunesfeed' => '\Zend\Feed\Writer\Extension\ITunes\Feed',
      'feed.writer.itunesrendererentry' => '\Zend\Feed\Writer\Extension\ITunes\Renderer\Entry',
      'feed.writer.itunesrendererfeed' => '\Zend\Feed\Writer\Extension\ITunes\Renderer\Feed',
      'feed.writer.slashrendererentry' => '\Zend\Feed\Writer\Extension\Slash\Renderer\Entry',
      'feed.writer.threadingrendererentry' => '\Zend\Feed\Writer\Extension\Threading\Renderer\Entry',
      'feed.writer.wellformedwebrendererentry' => '\Zend\Feed\Writer\Extension\WellFormedWeb\Renderer\Entry',
      'theme.manager' => '\Drupal\Core\Theme\ThemeManager',
      'theme.initialization' => '\Drupal\Core\Theme\ThemeInitialization',
      'theme.registry' => '\Drupal\Core\Theme\Registry',
      'authentication' => '\Drupal\Core\Authentication\AuthenticationManager',
      'authentication_collector' => '\Drupal\Core\Authentication\AuthenticationCollector',
      'authentication_subscriber' => '\Drupal\Core\EventSubscriber\AuthenticationSubscriber',
      'account_switcher' => '\Drupal\Core\Session\AccountSwitcher',
      'user_permissions_hash_generator' => '\Drupal\Core\Session\PermissionsHashGenerator',
      'current_user' => '\Drupal\Core\Session\AccountProxy',
      'session_configuration' => '\Drupal\Core\Session\SessionConfiguration',
      'session' => '\Symfony\Component\HttpFoundation\Session\Session',
      'session_handler.storage' => '\Drupal\Core\Session\SessionHandler',
      'session_handler.write_safe' => '\Drupal\Core\Session\WriteSafeSessionHandler',
      'session_manager' => '\Drupal\Core\Session\SessionManager',
      'session_manager.metadata_bag' => '\Drupal\Core\Session\MetadataBag',
      'asset.css.collection_renderer' => '\Drupal\Core\Asset\CssCollectionRenderer',
      'asset.css.collection_optimizer' => '\Drupal\Core\Asset\CssCollectionOptimizer',
      'asset.css.optimizer' => '\Drupal\Core\Asset\CssOptimizer',
      'asset.css.collection_grouper' => '\Drupal\Core\Asset\CssCollectionGrouper',
      'asset.css.dumper' => '\Drupal\Core\Asset\AssetDumper',
      'asset.js.collection_renderer' => '\Drupal\Core\Asset\JsCollectionRenderer',
      'asset.js.collection_optimizer' => '\Drupal\Core\Asset\JsCollectionOptimizer',
      'asset.js.optimizer' => '\Drupal\Core\Asset\JsOptimizer',
      'asset.js.collection_grouper' => '\Drupal\Core\Asset\JsCollectionGrouper',
      'asset.js.dumper' => '\Drupal\Core\Asset\AssetDumper',
      'library.discovery' => '\Drupal\Core\Asset\LibraryDiscovery',
      'library.discovery.collector' => '\Drupal\Core\Asset\LibraryDiscoveryCollector',
      'library.discovery.parser' => '\Drupal\Core\Asset\LibraryDiscoveryParser',
      'library.dependency_resolver' => '\Drupal\Core\Asset\LibraryDependencyResolver',
      'asset.resolver' => '\Drupal\Core\Asset\AssetResolver',
      'info_parser' => '\Drupal\Core\Extension\InfoParser',
      'twig' => '\Drupal\Core\Template\TwigEnvironment',
      'twig.extension' => '\Drupal\Core\Template\TwigExtension',
      'twig.extension.debug' => '\Twig_Extension_Debug',
      'twig.loader.filesystem' => '\Drupal\Core\Template\Loader\FilesystemLoader',
      'twig.loader.theme_registry' => '\Drupal\Core\Template\Loader\ThemeRegistryLoader',
      'twig.loader.string' => '\Drupal\Core\Template\Loader\StringLoader',
      'file.htaccess_writer' => '\Drupal\Core\File\HtaccessWriter',
      'file.mime_type.guesser' => '\Drupal\Core\ProxyClass\File\MimeType\MimeTypeGuesser',
      'file.mime_type.guesser.extension' => '\Drupal\Core\ProxyClass\File\MimeType\ExtensionMimeTypeGuesser',
      'render_placeholder_generator' => '\Drupal\Core\Render\PlaceholderGenerator',
      'render_cache' => '\Drupal\Core\Render\PlaceholderingRenderCache',
      'renderer' => '\Drupal\Core\Render\Renderer',
      'early_rendering_controller_wrapper_subscriber' => '\Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber',
      'html_response.placeholder_strategy_subscriber' => '\Drupal\Core\EventSubscriber\HtmlResponsePlaceholderStrategySubscriber',
      'placeholder_strategy' => '\Drupal\Core\Render\Placeholder\ChainedPlaceholderStrategy',
      'placeholder_strategy.single_flush' => '\Drupal\Core\Render\Placeholder\SingleFlushStrategy',
      'email.validator' => '\Drupal\Component\Utility\EmailValidator',
      'update.post_update_registry' => '\Drupal\Core\Update\UpdateRegistry',
      'update.post_update_registry_factory' => '\Drupal\Core\Update\UpdateRegistryFactory',
      'uuid' => '\Drupal\Component\Uuid\Php',
      'response_filter.active_link' => '\Drupal\Core\EventSubscriber\ActiveLinkResponseFilter',
      'response_filter.rss.relative_url' => '\Drupal\Core\EventSubscriber\RssResponseRelativeUrlFilter',
      'messenger' => '\Drupal\Core\Messenger\Messenger',
      'tempstore.private' => '\Drupal\Core\TempStore\PrivateTempStoreFactory',
      'tempstore.shared' => '\Drupal\Core\TempStore\SharedTempStoreFactory',
      'pager.manager' => '\Drupal\Core\Pager\PagerManager',
      'pager.parameters' => '\Drupal\Core\Pager\PagerParameters',
      'admin_toolbar_search.search_links' => '\Drupal\admin_toolbar_search\SearchLinks',
      'admin_toolbar_tools.helper' => '\Drupal\admin_toolbar_tools\AdminToolbarToolsHelper',
      'alter.cron' => '\Drupal\alter\ProxyClass\CronAlter',
      'automated_cron.subscriber' => '\Drupal\automated_cron\EventSubscriber\AutomatedCron',
      'html_response.big_pipe_subscriber' => '\Drupal\big_pipe\EventSubscriber\HtmlResponseBigPipeSubscriber',
      'placeholder_strategy.big_pipe' => '\Drupal\big_pipe\Render\Placeholder\BigPipeStrategy',
      'big_pipe' => '\Drupal\big_pipe\Render\BigPipe',
      'route_subscriber.no_big_pipe' => '\Drupal\big_pipe\EventSubscriber\NoBigPipeRouteAlterSubscriber',
      'theme.negotiator.block.admin_demo' => '\Drupal\block\Theme\AdminDemoNegotiator',
      'block.page_display_variant_subscriber' => '\Drupal\block\EventSubscriber\BlockPageDisplayVariantSubscriber',
      'block.repository' => '\Drupal\block\BlockRepository',
      'breakpoint.manager' => '\Drupal\breakpoint\BreakpointManager',
      'config.config_subscriber' => '\Drupal\config\ConfigSubscriber',
      'config_translation.route_subscriber' => '\Drupal\config_translation\Routing\RouteSubscriber',
      'config_translation.access.overview' => '\Drupal\config_translation\Access\ConfigTranslationOverviewAccess',
      'config_translation.access.form' => '\Drupal\config_translation\Access\ConfigTranslationFormAccess',
      'plugin.manager.config_translation.mapper' => '\Drupal\config_translation\ConfigMapperManager',
      'logger.dblog' => '\Drupal\dblog\Logger\DbLog',
      'cache.dynamic_page_cache' => '\Drupal\Core\Cache\CacheBackendInterface',
      'dynamic_page_cache_subscriber' => '\Drupal\dynamic_page_cache\EventSubscriber\DynamicPageCacheSubscriber',
      'dynamic_page_cache_request_policy' => '\Drupal\dynamic_page_cache\PageCache\RequestPolicy\DefaultRequestPolicy',
      'dynamic_page_cache_response_policy' => '\Drupal\Core\ProxyClass\PageCache\ChainResponsePolicy',
      'entity_reference_revisions.orphan_purger' => '\Drupal\entity_reference_revisions\EntityReferenceRevisionsOrphanPurger',
      'field.uninstall_validator' => '\Drupal\field\ProxyClass\FieldUninstallValidator',
      'field_ui.subscriber' => '\Drupal\field_ui\Routing\RouteSubscriber',
      'field_ui.route_enhancer' => '\Drupal\field_ui\Routing\FieldUiRouteEnhancer',
      'access_check.field_ui.view_mode' => '\Drupal\field_ui\Access\ViewModeAccessCheck',
      'access_check.field_ui.form_mode' => '\Drupal\field_ui\Access\FormModeAccessCheck',
      'file.usage' => '\Drupal\file\FileUsage\DatabaseFileUsageBackend',
      'plugin.manager.filter' => '\Drupal\filter\FilterPluginManager',
      'filter.uninstall_validator' => '\Drupal\filter\ProxyClass\FilterUninstallValidator',
      'path_processor.image_styles' => '\Drupal\image\PathProcessor\PathProcessorImageStyles',
      'plugin.manager.image.effect' => '\Drupal\image\ImageEffectManager',
      'imdb.helper' => '\Drupal\imdb\IMDbHelper',
      'plugin.manager.imdb_queue' => '\Drupal\imdb\IMDbQueueManager',
      'entity_finder' => '\Drupal\imdb\EntityFinder',
      'plugin.manager.imdb_saver' => '\Drupal\imdb_saver\IMDbSaverManager',
      'plugin.manager.language_negotiation_method' => '\Drupal\language\LanguageNegotiationMethodManager',
      'language_negotiator' => '\Drupal\language\LanguageNegotiator',
      'language.config_subscriber' => '\Drupal\language\EventSubscriber\ConfigSubscriber',
      'language.config_factory_override' => '\Drupal\language\Config\LanguageConfigFactoryOverride',
      'language_converter' => '\Drupal\language\ProxyClass\LanguageConverter',
      'locale.config_manager' => '\Drupal\locale\LocaleConfigManager',
      'locale.storage' => '\Drupal\locale\StringDatabaseStorage',
      'locale.project' => '\Drupal\locale\LocaleProjectStorage',
      'locale.plural.formula' => '\Drupal\locale\PluralFormula',
      'string_translator.locale.lookup' => '\Drupal\locale\LocaleTranslation',
      'stream_wrapper.translations' => '\Drupal\locale\StreamWrapper\TranslationsStream',
      'locale.config_subscriber' => '\Drupal\locale\LocaleConfigSubscriber',
      'locale.locale_translation_cache_tag' => '\Drupal\locale\EventSubscriber\LocaleTranslationCacheTag',
      'plugin.manager.media.source' => '\Drupal\media\MediaSourceManager',
      'access_check.media.revision' => '\Drupal\media\Access\MediaRevisionAccessCheck',
      'media.oembed.url_resolver' => '\Drupal\media\OEmbed\UrlResolver',
      'media.oembed.provider_repository' => '\Drupal\media\OEmbed\ProviderRepository',
      'media.oembed.resource_fetcher' => '\Drupal\media\OEmbed\ResourceFetcher',
      'media.oembed.iframe_url_helper' => '\Drupal\media\IFrameUrlHelper',
      'media.config_subscriber' => '\Drupal\media\EventSubscriber\MediaConfigSubscriber',
      'media_library.ui_builder' => '\Drupal\media_library\MediaLibraryUiBuilder',
      'media_library.route_subscriber' => '\Drupal\media_library\Routing\RouteSubscriber',
      'media_library.opener_resolver' => '\Drupal\media_library\OpenerResolver',
      'media_library.opener.field_widget' => '\Drupal\media_library\MediaLibraryFieldWidgetOpener',
      'media_library.opener.editor' => '\Drupal\media_library\MediaLibraryEditorOpener',
      'module_filter.route_subscriber' => '\Drupal\module_filter\Routing\RouteSubscriber',
      'node.route_subscriber' => '\Drupal\node\Routing\RouteSubscriber',
      'node.grant_storage' => '\Drupal\node\NodeGrantDatabaseStorage',
      'access_check.node.revision' => '\Drupal\node\Access\NodeRevisionAccessCheck',
      'access_check.node.add' => '\Drupal\node\Access\NodeAddAccessCheck',
      'access_check.node.preview' => '\Drupal\node\Access\NodePreviewAccessCheck',
      'node.admin_path.route_subscriber' => '\Drupal\node\EventSubscriber\NodeAdminRouteSubscriber',
      'node_preview' => '\Drupal\node\ProxyClass\ParamConverter\NodePreviewConverter',
      'cache_context.user.node_grants' => '\Drupal\node\Cache\NodeAccessGrantsCacheContext',
      'node.node_route_context' => '\Drupal\node\ContextProvider\NodeRouteContext',
      'http_middleware.page_cache' => '\Drupal\page_cache\StackMiddleware\PageCache',
      'cache.page' => '\Drupal\Core\Cache\CacheBackendInterface',
      'path_alias.subscriber' => '\Drupal\path_alias\EventSubscriber\PathAliasSubscriber',
      'path_alias.path_processor' => '\Drupal\path_alias\PathProcessor\AliasPathProcessor',
      'path_alias.manager' => '\Drupal\path_alias\AliasManager',
      'path_alias.repository' => '\Drupal\path_alias\AliasRepository',
      'path_alias.whitelist' => '\Drupal\path_alias\AliasWhitelist',
      'remover.thread_manager' => '\Drupal\remover\RemoverThreadManager',
      'access_check.cron' => '\Drupal\system\Access\CronAccessCheck',
      'access_check.db_update' => '\Drupal\system\Access\DbUpdateAccessCheck',
      'system.manager' => '\Drupal\system\SystemManager',
      'system.breadcrumb.default' => '\Drupal\system\PathBasedBreadcrumbBuilder',
      'path_processor.files' => '\Drupal\system\PathProcessor\PathProcessorFiles',
      'system.admin_path.route_subscriber' => '\Drupal\system\EventSubscriber\AdminRouteSubscriber',
      'theme.negotiator.system.batch' => '\Drupal\system\Theme\BatchNegotiator',
      'theme.negotiator.system.db_update' => '\Drupal\system\Theme\DbUpdateNegotiator',
      'system.config_subscriber' => '\Drupal\system\SystemConfigSubscriber',
      'system.config_cache_tag' => '\Drupal\system\EventSubscriber\ConfigCacheTag',
      'system.timezone_resolver' => '\Drupal\system\TimeZoneResolver',
      'taxonomy_term.breadcrumb' => '\Drupal\taxonomy\TermBreadcrumbBuilder',
      'cache.toolbar' => '\Drupal\Core\Cache\CacheBackendInterface',
      'toolbar.page_cache_request_policy.allow_toolbar_path' => '\Drupal\toolbar\PageCache\AllowToolbarPath',
      'toolbar.menu_tree' => '\Drupal\toolbar\Menu\ToolbarMenuLinkTree',
      'access_check.update.manager_access' => '\Drupal\update\Access\UpdateManagerAccessCheck',
      'update.manager' => '\Drupal\update\UpdateManager',
      'update.processor' => '\Drupal\update\UpdateProcessor',
      'update.fetcher' => '\Drupal\update\UpdateFetcher',
      'update.root' => '\SplString',
      'access_check.permission' => '\Drupal\user\Access\PermissionAccessCheck',
      'access_check.user.register' => '\Drupal\user\Access\RegisterAccessCheck',
      'access_check.user.role' => '\Drupal\user\Access\RoleAccessCheck',
      'access_check.user.login_status' => '\Drupal\user\Access\LoginStatusCheck',
      'user.authentication.cookie' => '\Drupal\user\Authentication\Provider\Cookie',
      'user.data' => '\Drupal\user\UserData',
      'user_maintenance_mode_subscriber' => '\Drupal\user\EventSubscriber\MaintenanceModeSubscriber',
      'user_access_denied_subscriber' => '\Drupal\user\EventSubscriber\AccessDeniedSubscriber',
      'user_last_access_subscriber' => '\Drupal\user\EventSubscriber\UserRequestSubscriber',
      'theme.negotiator.admin_theme' => '\Drupal\user\Theme\AdminNegotiator',
      'user.auth' => '\Drupal\user\UserAuth',
      'user.private_tempstore' => '\Drupal\user\PrivateTempStoreFactory',
      'user.shared_tempstore' => '\Drupal\user\SharedTempStoreFactory',
      'user.permissions' => '\Drupal\user\PermissionHandler',
      'user.current_user_context' => '\Drupal\user\ContextProvider\CurrentUserContext',
      'user.toolbar_link_builder' => '\Drupal\user\ToolbarLinkBuilder',
      'paramconverter.views_ui' => '\Drupal\views_ui\ProxyClass\ParamConverter\ViewUIConverter',
      'content_translation.synchronizer' => '\Drupal\content_translation\FieldTranslationSynchronizer',
      'content_translation.subscriber' => '\Drupal\content_translation\Routing\ContentTranslationRouteSubscriber',
      'content_translation.delete_access' => '\Drupal\content_translation\Access\ContentTranslationDeleteAccess',
      'content_translation.overview_access' => '\Drupal\content_translation\Access\ContentTranslationOverviewAccess',
      'content_translation.manage_access' => '\Drupal\content_translation\Access\ContentTranslationManageAccessCheck',
      'content_translation.manager' => '\Drupal\content_translation\ContentTranslationManager',
      'content_translation.updates_manager' => '\Drupal\content_translation\ContentTranslationUpdatesManager',
      'plugin.manager.views.access' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.area' => '\Drupal\views\Plugin\ViewsHandlerManager',
      'plugin.manager.views.argument' => '\Drupal\views\Plugin\ViewsHandlerManager',
      'plugin.manager.views.argument_default' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.argument_validator' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.cache' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.display_extender' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.display' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.exposed_form' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.field' => '\Drupal\views\Plugin\ViewsHandlerManager',
      'plugin.manager.views.filter' => '\Drupal\views\Plugin\ViewsHandlerManager',
      'plugin.manager.views.join' => '\Drupal\views\Plugin\ViewsHandlerManager',
      'plugin.manager.views.pager' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.query' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.relationship' => '\Drupal\views\Plugin\ViewsHandlerManager',
      'plugin.manager.views.row' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.sort' => '\Drupal\views\Plugin\ViewsHandlerManager',
      'plugin.manager.views.style' => '\Drupal\views\Plugin\ViewsPluginManager',
      'plugin.manager.views.wizard' => '\Drupal\views\Plugin\ViewsPluginManager',
      'views.views_data' => '\Drupal\views\ViewsData',
      'views.views_data_helper' => '\Drupal\views\ViewsDataHelper',
      'views.executable' => '\Drupal\views\ViewExecutableFactory',
      'views.analyzer' => '\Drupal\views\Analyzer',
      'views.route_subscriber' => '\Drupal\views\EventSubscriber\RouteSubscriber',
      'views.exposed_form_cache' => '\Drupal\views\ExposedFormCache',
      'views.entity_schema_subscriber' => '\Drupal\views\EventSubscriber\ViewsEntitySchemaSubscriber',
      'views.date_sql' => '\Drupal\views\Plugin\views\query\MysqlDateSql',
      'plugin.manager.paragraphs.behavior' => '\Drupal\paragraphs\ParagraphsBehaviorManager',
      'paragraphs_type.uuid_lookup' => '\Drupal\paragraphs\ParagraphsTypeIconUuidLookup',
      'config.commands' => '\Drush\Drupal\Commands\config\ConfigCommands',
      'config.export.commands' => '\Drush\Drupal\Commands\config\ConfigExportCommands',
      'config.import.commands' => '\Drush\Drupal\Commands\config\ConfigImportCommands',
      'batch.commands' => '\Drush\Drupal\Commands\core\BatchCommands',
      'cli.commands' => '\Drush\Drupal\Commands\core\CliCommands',
      'drupal.commands' => '\Drush\Drupal\Commands\core\DrupalCommands',
      'entity.commands' => '\Drush\Drupal\Commands\core\EntityCommands',
      'image.commands' => '\Drush\Drupal\Commands\core\ImageCommands',
      'jsonapi.commands' => '\Drush\Drupal\Commands\core\JsonapiCommands',
      'language.commands' => '\Drush\Drupal\Commands\core\LanguageCommands',
      'locale.commands' => '\Drush\Drupal\Commands\core\LocaleCommands',
      'messenger.commands' => '\Drush\Drupal\Commands\core\MessengerCommands',
      'queue.commands' => '\Drush\Drupal\Commands\core\QueueCommands',
      'role.commands' => '\Drush\Drupal\Commands\core\RoleCommands',
      'state.commands' => '\Drush\Drupal\Commands\core\StateCommands',
      'twig.commands' => '\Drush\Drupal\Commands\core\TwigCommands',
      'user.commands' => '\Drush\Drupal\Commands\core\UserCommands',
      'views.commands' => '\Drush\Drupal\Commands\core\ViewsCommands',
      'watchdog.commands' => '\Drush\Drupal\Commands\core\WatchdogCommands',
      'pm.commands' => '\Drush\Drupal\Commands\pm\PmCommands',
      'theme.commands' => '\Drush\Drupal\Commands\pm\ThemeCommands',
      'sanitize.commands' => '\Drush\Drupal\Commands\sql\SanitizeCommands',
      'sanitize.comments.commands' => '\Drush\Drupal\Commands\sql\SanitizeCommentsCommands',
      'sanitize.sessions.commands' => '\Drush\Drupal\Commands\sql\SanitizeSessionsCommands',
      'sanitize.userfields.commands' => '\Drush\Drupal\Commands\sql\SanitizeUserFieldsCommands',
      'sanitize.usertable.commands' => '\Drush\Drupal\Commands\sql\SanitizeUserTableCommands',
      'stream_wrapper.private' => '\Drupal\Core\StreamWrapper\PrivateStream',
      'language_request_subscriber' => '\Drupal\language\EventSubscriber\LanguageRequestSubscriber',
      'path_processor_language' => '\Drupal\language\HttpKernel\PathProcessorLanguage',
      'node.node_translation_exception' => '\Drupal\node\EventSubscriber\NodeTranslationExceptionSubscriber',
      'drupal.proxy_original_service.page_cache_response_policy' => '\Drupal\Core\PageCache\ChainResponsePolicy',
      'drupal.proxy_original_service.config.installer' => '\Drupal\Core\Config\ConfigInstaller',
      'drupal.proxy_original_service.cron' => '\Drupal\alter\CronAlter',
      'drupal.proxy_original_service.module_installer' => '\Drupal\Core\Extension\ModuleInstaller',
      'drupal.proxy_original_service.content_uninstall_validator' => '\Drupal\Core\Entity\ContentUninstallValidator',
      'drupal.proxy_original_service.required_module_uninstall_validator' => '\Drupal\Core\Extension\RequiredModuleUninstallValidator',
      'drupal.proxy_original_service.plugin.cache_clearer' => '\Drupal\Core\Plugin\CachedDiscoveryClearer',
      'drupal.proxy_original_service.paramconverter.menu_link' => '\Drupal\Core\ParamConverter\MenuLinkPluginConverter',
      'drupal.proxy_original_service.lock' => '\Drupal\Core\Lock\DatabaseLockBackend',
      'drupal.proxy_original_service.lock.persistent' => '\Drupal\Core\Lock\PersistentDatabaseLockBackend',
      'drupal.proxy_original_service.router.dumper' => '\Drupal\Core\Routing\MatcherDumper',
      'drupal.proxy_original_service.router.builder' => '\Drupal\Core\Routing\RouteBuilder',
      'drupal.proxy_original_service.paramconverter.configentity_admin' => '\Drupal\Core\ParamConverter\AdminPathConfigEntityConverter',
      'drupal.proxy_original_service.bare_html_page_renderer' => '\Drupal\Core\Render\BareHtmlPageRenderer',
      'drupal.proxy_original_service.batch.storage' => '\Drupal\Core\Batch\BatchStorage',
      'drupal.proxy_original_service.file.mime_type.guesser' => '\Drupal\Core\File\MimeType\MimeTypeGuesser',
      'drupal.proxy_original_service.file.mime_type.guesser.extension' => '\Drupal\Core\File\MimeType\ExtensionMimeTypeGuesser',
      'drupal.proxy_original_service.alter.cron' => '\Drupal\alter\CronAlter',
      'drupal.proxy_original_service.dynamic_page_cache_response_policy' => '\Drupal\Core\PageCache\ChainResponsePolicy',
      'drupal.proxy_original_service.field.uninstall_validator' => '\Drupal\field\FieldUninstallValidator',
      'drupal.proxy_original_service.filter.uninstall_validator' => '\Drupal\filter\FilterUninstallValidator',
      'drupal.proxy_original_service.language_converter' => '\Drupal\language\LanguageConverter',
      'drupal.proxy_original_service.node_preview' => '\Drupal\node\ParamConverter\NodePreviewConverter',
      'drupal.proxy_original_service.paramconverter.views_ui' => '\Drupal\views_ui\ParamConverter\ViewUIConverter',
      'html_response.attachments_processor' => '\Drupal\big_pipe\Render\BigPipeResponseAttachmentsProcessor',
    ])
  );

  override(
    \Drupal\Core\Entity\EntityTypeManagerInterface::getStorage(0),
    map([
      'block' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'field_config' => '\Drupal\field\FieldConfigStorage',
      'field_storage_config' => '\Drupal\field\FieldStorageConfigStorage',
      'file' => '\Drupal\file\FileStorage',
      'filter_format' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'image_style' => '\Drupal\image\ImageStyleStorage',
      'language_content_settings' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'configurable_language' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'media_type' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'media' => '\Drupal\media\MediaStorage',
      'node_type' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'node' => '\Drupal\node\NodeStorage',
      'path_alias' => '\Drupal\path_alias\PathAliasStorage',
      'rdf_mapping' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'responsive_image_style' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'action' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'menu' => '\Drupal\system\MenuStorage',
      'taxonomy_vocabulary' => '\Drupal\taxonomy\VocabularyStorage',
      'taxonomy_term' => '\Drupal\taxonomy\TermStorage',
      'user_role' => '\Drupal\user\RoleStorage',
      'user' => '\Drupal\user\UserStorage',
      'menu_link_content' => '\Drupal\menu_link_content\MenuLinkContentStorage',
      'view' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'paragraph' => '\Drupal\Core\Entity\Sql\SqlContentEntityStorage',
      'paragraphs_type' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'date_format' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'base_field_override' => '\Drupal\Core\Field\BaseFieldOverrideStorage',
      'entity_view_mode' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'entity_view_display' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'entity_form_mode' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
      'entity_form_display' => '\Drupal\Core\Config\Entity\ConfigEntityStorage',
    ])
  );

  override(
    \Drupal\Core\Entity\EntityTypeManagerInterface::getViewBuilder(0),
    map([
      'block' => '\Drupal\block\BlockViewBuilder',
      'file' => '\Drupal\Core\Entity\EntityViewBuilder',
      'media' => '\Drupal\Core\Entity\EntityViewBuilder',
      'node' => '\Drupal\node\NodeViewBuilder',
      'path_alias' => '\Drupal\Core\Entity\EntityViewBuilder',
      'taxonomy_term' => '\Drupal\Core\Entity\EntityViewBuilder',
      'user' => '\Drupal\Core\Entity\EntityViewBuilder',
      'menu_link_content' => '\Drupal\Core\Entity\EntityViewBuilder',
      'paragraph' => '\Drupal\paragraphs\ParagraphViewBuilder',
    ])
  );

  override(
    \Drupal\Core\Entity\EntityTypeManagerInterface::getListBuilder(0),
    map([
      'block' => '\Drupal\block\BlockListBuilder',
      'field_config' => '\Drupal\field_ui\FieldConfigListBuilder',
      'field_storage_config' => '\Drupal\field_ui\FieldStorageConfigListBuilder',
      'filter_format' => '\Drupal\filter\FilterFormatListBuilder',
      'image_style' => '\Drupal\image\ImageStyleListBuilder',
      'configurable_language' => '\Drupal\language\LanguageListBuilder',
      'media_type' => '\Drupal\media\MediaTypeListBuilder',
      'media' => '\Drupal\media\MediaListBuilder',
      'node_type' => '\Drupal\node\NodeTypeListBuilder',
      'node' => '\Drupal\node\NodeListBuilder',
      'responsive_image_style' => '\Drupal\responsive_image\ResponsiveImageStyleListBuilder',
      'menu' => '\Drupal\menu_ui\MenuListBuilder',
      'taxonomy_vocabulary' => '\Drupal\taxonomy\VocabularyListBuilder',
      'taxonomy_term' => '\Drupal\Core\Entity\EntityListBuilder',
      'user_role' => '\Drupal\user\RoleListBuilder',
      'user' => '\Drupal\user\UserListBuilder',
      'view' => '\Drupal\views_ui\ViewListBuilder',
      'paragraphs_type' => '\Drupal\paragraphs\Controller\ParagraphsTypeListBuilder',
      'date_format' => '\Drupal\system\DateFormatListBuilder',
      'entity_view_mode' => '\Drupal\field_ui\EntityDisplayModeListBuilder',
      'entity_form_mode' => '\Drupal\field_ui\EntityFormModeListBuilder',
    ])
  );

  override(
    \Drupal\Core\Entity\EntityTypeManagerInterface::getAccessControlHandler(0),
    map([
     'block' => '\Drupal\block\BlockAccessControlHandler',
     'field_config' => '\Drupal\field\FieldConfigAccessControlHandler',
     'field_storage_config' => '\Drupal\field\FieldStorageConfigAccessControlHandler',
     'file' => '\Drupal\file\FileAccessControlHandler',
     'filter_format' => '\Drupal\filter\FilterFormatAccessControlHandler',
     'image_style' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'language_content_settings' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'configurable_language' => '\Drupal\language\LanguageAccessControlHandler',
     'media_type' => '\Drupal\media\MediaTypeAccessControlHandler',
     'media' => '\Drupal\media\MediaAccessControlHandler',
     'node_type' => '\Drupal\node\NodeTypeAccessControlHandler',
     'node' => '\Drupal\node\NodeAccessControlHandler',
     'path_alias' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'rdf_mapping' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'responsive_image_style' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'action' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'menu' => '\Drupal\system\MenuAccessControlHandler',
     'taxonomy_vocabulary' => '\Drupal\taxonomy\VocabularyAccessControlHandler',
     'taxonomy_term' => '\Drupal\taxonomy\TermAccessControlHandler',
     'user_role' => '\Drupal\user\RoleAccessControlHandler',
     'user' => '\Drupal\user\UserAccessControlHandler',
     'menu_link_content' => '\Drupal\menu_link_content\MenuLinkContentAccessControlHandler',
     'view' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'paragraph' => '\Drupal\paragraphs\ParagraphAccessControlHandler',
     'paragraphs_type' => '\Drupal\paragraphs\ParagraphsTypeAccessControlHandler',
     'date_format' => '\Drupal\system\DateFormatAccessControlHandler',
     'base_field_override' => '\Drupal\Core\Field\BaseFieldOverrideAccessControlHandler',
     'entity_view_mode' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'entity_view_display' => '\Drupal\Core\Entity\Entity\Access\EntityViewDisplayAccessControlHandler',
     'entity_form_mode' => '\Drupal\Core\Entity\EntityAccessControlHandler',
     'entity_form_display' => '\Drupal\Core\Entity\Entity\Access\EntityFormDisplayAccessControlHandler',
    ])
  );

  override(\Drupal\block\Entity\Block::loadMultiple(), map(['' => '\Drupal\block\Entity\Block[]']));
  override(\Drupal\block\Entity\Block::load(), map(['' => '\Drupal\block\Entity\Block']));
  override(\Drupal\block\Entity\Block::create(), map(['' => '\Drupal\block\Entity\Block']));

  override(\Drupal\field\Entity\FieldConfig::loadMultiple(), map(['' => '\Drupal\field\Entity\FieldConfig[]']));
  override(\Drupal\field\Entity\FieldConfig::load(), map(['' => '\Drupal\field\Entity\FieldConfig']));
  override(\Drupal\field\Entity\FieldConfig::create(), map(['' => '\Drupal\field\Entity\FieldConfig']));

  override(\Drupal\field\Entity\FieldStorageConfig::loadMultiple(), map(['' => '\Drupal\field\Entity\FieldStorageConfig[]']));
  override(\Drupal\field\Entity\FieldStorageConfig::load(), map(['' => '\Drupal\field\Entity\FieldStorageConfig']));
  override(\Drupal\field\Entity\FieldStorageConfig::create(), map(['' => '\Drupal\field\Entity\FieldStorageConfig']));

  override(\Drupal\file\Entity\File::loadMultiple(), map(['' => '\Drupal\file\Entity\File[]']));
  override(\Drupal\file\Entity\File::load(), map(['' => '\Drupal\file\Entity\File']));
  override(\Drupal\file\Entity\File::create(), map(['' => '\Drupal\file\Entity\File']));

  override(\Drupal\filter\Entity\FilterFormat::loadMultiple(), map(['' => '\Drupal\filter\Entity\FilterFormat[]']));
  override(\Drupal\filter\Entity\FilterFormat::load(), map(['' => '\Drupal\filter\Entity\FilterFormat']));
  override(\Drupal\filter\Entity\FilterFormat::create(), map(['' => '\Drupal\filter\Entity\FilterFormat']));

  override(\Drupal\image\Entity\ImageStyle::loadMultiple(), map(['' => '\Drupal\image\Entity\ImageStyle[]']));
  override(\Drupal\image\Entity\ImageStyle::load(), map(['' => '\Drupal\image\Entity\ImageStyle']));
  override(\Drupal\image\Entity\ImageStyle::create(), map(['' => '\Drupal\image\Entity\ImageStyle']));

  override(\Drupal\language\Entity\ContentLanguageSettings::loadMultiple(), map(['' => '\Drupal\language\Entity\ContentLanguageSettings[]']));
  override(\Drupal\language\Entity\ContentLanguageSettings::load(), map(['' => '\Drupal\language\Entity\ContentLanguageSettings']));
  override(\Drupal\language\Entity\ContentLanguageSettings::create(), map(['' => '\Drupal\language\Entity\ContentLanguageSettings']));

  override(\Drupal\language\Entity\ConfigurableLanguage::loadMultiple(), map(['' => '\Drupal\language\Entity\ConfigurableLanguage[]']));
  override(\Drupal\language\Entity\ConfigurableLanguage::load(), map(['' => '\Drupal\language\Entity\ConfigurableLanguage']));
  override(\Drupal\language\Entity\ConfigurableLanguage::create(), map(['' => '\Drupal\language\Entity\ConfigurableLanguage']));

  override(\Drupal\media\Entity\MediaType::loadMultiple(), map(['' => '\Drupal\media\Entity\MediaType[]']));
  override(\Drupal\media\Entity\MediaType::load(), map(['' => '\Drupal\media\Entity\MediaType']));
  override(\Drupal\media\Entity\MediaType::create(), map(['' => '\Drupal\media\Entity\MediaType']));

  override(\Drupal\media\Entity\Media::loadMultiple(), map(['' => '\Drupal\media\Entity\Media[]']));
  override(\Drupal\media\Entity\Media::load(), map(['' => '\Drupal\media\Entity\Media']));
  override(\Drupal\media\Entity\Media::create(), map(['' => '\Drupal\media\Entity\Media']));

  override(\Drupal\node\Entity\NodeType::loadMultiple(), map(['' => '\Drupal\node\Entity\NodeType[]']));
  override(\Drupal\node\Entity\NodeType::load(), map(['' => '\Drupal\node\Entity\NodeType']));
  override(\Drupal\node\Entity\NodeType::create(), map(['' => '\Drupal\node\Entity\NodeType']));

  override(\Drupal\node\Entity\Node::loadMultiple(), map(['' => '\Drupal\node\Entity\Node[]']));
  override(\Drupal\node\Entity\Node::load(), map(['' => '\Drupal\node\Entity\Node']));
  override(\Drupal\node\Entity\Node::create(), map(['' => '\Drupal\node\Entity\Node']));

  override(\Drupal\path_alias\Entity\PathAlias::loadMultiple(), map(['' => '\Drupal\path_alias\Entity\PathAlias[]']));
  override(\Drupal\path_alias\Entity\PathAlias::load(), map(['' => '\Drupal\path_alias\Entity\PathAlias']));
  override(\Drupal\path_alias\Entity\PathAlias::create(), map(['' => '\Drupal\path_alias\Entity\PathAlias']));

  override(\Drupal\rdf\Entity\RdfMapping::loadMultiple(), map(['' => '\Drupal\rdf\Entity\RdfMapping[]']));
  override(\Drupal\rdf\Entity\RdfMapping::load(), map(['' => '\Drupal\rdf\Entity\RdfMapping']));
  override(\Drupal\rdf\Entity\RdfMapping::create(), map(['' => '\Drupal\rdf\Entity\RdfMapping']));

  override(\Drupal\responsive_image\Entity\ResponsiveImageStyle::loadMultiple(), map(['' => '\Drupal\responsive_image\Entity\ResponsiveImageStyle[]']));
  override(\Drupal\responsive_image\Entity\ResponsiveImageStyle::load(), map(['' => '\Drupal\responsive_image\Entity\ResponsiveImageStyle']));
  override(\Drupal\responsive_image\Entity\ResponsiveImageStyle::create(), map(['' => '\Drupal\responsive_image\Entity\ResponsiveImageStyle']));

  override(\Drupal\system\Entity\Action::loadMultiple(), map(['' => '\Drupal\system\Entity\Action[]']));
  override(\Drupal\system\Entity\Action::load(), map(['' => '\Drupal\system\Entity\Action']));
  override(\Drupal\system\Entity\Action::create(), map(['' => '\Drupal\system\Entity\Action']));

  override(\Drupal\system\Entity\Menu::loadMultiple(), map(['' => '\Drupal\system\Entity\Menu[]']));
  override(\Drupal\system\Entity\Menu::load(), map(['' => '\Drupal\system\Entity\Menu']));
  override(\Drupal\system\Entity\Menu::create(), map(['' => '\Drupal\system\Entity\Menu']));

  override(\Drupal\taxonomy\Entity\Vocabulary::loadMultiple(), map(['' => '\Drupal\taxonomy\Entity\Vocabulary[]']));
  override(\Drupal\taxonomy\Entity\Vocabulary::load(), map(['' => '\Drupal\taxonomy\Entity\Vocabulary']));
  override(\Drupal\taxonomy\Entity\Vocabulary::create(), map(['' => '\Drupal\taxonomy\Entity\Vocabulary']));

  override(\Drupal\taxonomy\Entity\Term::loadMultiple(), map(['' => '\Drupal\taxonomy\Entity\Term[]']));
  override(\Drupal\taxonomy\Entity\Term::load(), map(['' => '\Drupal\taxonomy\Entity\Term']));
  override(\Drupal\taxonomy\Entity\Term::create(), map(['' => '\Drupal\taxonomy\Entity\Term']));

  override(\Drupal\user\Entity\Role::loadMultiple(), map(['' => '\Drupal\user\Entity\Role[]']));
  override(\Drupal\user\Entity\Role::load(), map(['' => '\Drupal\user\Entity\Role']));
  override(\Drupal\user\Entity\Role::create(), map(['' => '\Drupal\user\Entity\Role']));

  override(\Drupal\user\Entity\User::loadMultiple(), map(['' => '\Drupal\user\Entity\User[]']));
  override(\Drupal\user\Entity\User::load(), map(['' => '\Drupal\user\Entity\User']));
  override(\Drupal\user\Entity\User::create(), map(['' => '\Drupal\user\Entity\User']));

  override(\Drupal\menu_link_content\Entity\MenuLinkContent::loadMultiple(), map(['' => '\Drupal\menu_link_content\Entity\MenuLinkContent[]']));
  override(\Drupal\menu_link_content\Entity\MenuLinkContent::load(), map(['' => '\Drupal\menu_link_content\Entity\MenuLinkContent']));
  override(\Drupal\menu_link_content\Entity\MenuLinkContent::create(), map(['' => '\Drupal\menu_link_content\Entity\MenuLinkContent']));

  override(\Drupal\views\Entity\View::loadMultiple(), map(['' => '\Drupal\views\Entity\View[]']));
  override(\Drupal\views\Entity\View::load(), map(['' => '\Drupal\views\Entity\View']));
  override(\Drupal\views\Entity\View::create(), map(['' => '\Drupal\views\Entity\View']));

  override(\Drupal\paragraphs\Entity\Paragraph::loadMultiple(), map(['' => '\Drupal\paragraphs\Entity\Paragraph[]']));
  override(\Drupal\paragraphs\Entity\Paragraph::load(), map(['' => '\Drupal\paragraphs\Entity\Paragraph']));
  override(\Drupal\paragraphs\Entity\Paragraph::create(), map(['' => '\Drupal\paragraphs\Entity\Paragraph']));

  override(\Drupal\paragraphs\Entity\ParagraphsType::loadMultiple(), map(['' => '\Drupal\paragraphs\Entity\ParagraphsType[]']));
  override(\Drupal\paragraphs\Entity\ParagraphsType::load(), map(['' => '\Drupal\paragraphs\Entity\ParagraphsType']));
  override(\Drupal\paragraphs\Entity\ParagraphsType::create(), map(['' => '\Drupal\paragraphs\Entity\ParagraphsType']));

  override(\Drupal\Core\Datetime\Entity\DateFormat::loadMultiple(), map(['' => '\Drupal\Core\Datetime\Entity\DateFormat[]']));
  override(\Drupal\Core\Datetime\Entity\DateFormat::load(), map(['' => '\Drupal\Core\Datetime\Entity\DateFormat']));
  override(\Drupal\Core\Datetime\Entity\DateFormat::create(), map(['' => '\Drupal\Core\Datetime\Entity\DateFormat']));

  override(\Drupal\Core\Field\Entity\BaseFieldOverride::loadMultiple(), map(['' => '\Drupal\Core\Field\Entity\BaseFieldOverride[]']));
  override(\Drupal\Core\Field\Entity\BaseFieldOverride::load(), map(['' => '\Drupal\Core\Field\Entity\BaseFieldOverride']));
  override(\Drupal\Core\Field\Entity\BaseFieldOverride::create(), map(['' => '\Drupal\Core\Field\Entity\BaseFieldOverride']));

  override(\Drupal\Core\Entity\Entity\EntityViewMode::loadMultiple(), map(['' => '\Drupal\Core\Entity\Entity\EntityViewMode[]']));
  override(\Drupal\Core\Entity\Entity\EntityViewMode::load(), map(['' => '\Drupal\Core\Entity\Entity\EntityViewMode']));
  override(\Drupal\Core\Entity\Entity\EntityViewMode::create(), map(['' => '\Drupal\Core\Entity\Entity\EntityViewMode']));

  override(\Drupal\Core\Entity\Entity\EntityViewDisplay::loadMultiple(), map(['' => '\Drupal\Core\Entity\Entity\EntityViewDisplay[]']));
  override(\Drupal\Core\Entity\Entity\EntityViewDisplay::load(), map(['' => '\Drupal\Core\Entity\Entity\EntityViewDisplay']));
  override(\Drupal\Core\Entity\Entity\EntityViewDisplay::create(), map(['' => '\Drupal\Core\Entity\Entity\EntityViewDisplay']));

  override(\Drupal\Core\Entity\Entity\EntityFormMode::loadMultiple(), map(['' => '\Drupal\Core\Entity\Entity\EntityFormMode[]']));
  override(\Drupal\Core\Entity\Entity\EntityFormMode::load(), map(['' => '\Drupal\Core\Entity\Entity\EntityFormMode']));
  override(\Drupal\Core\Entity\Entity\EntityFormMode::create(), map(['' => '\Drupal\Core\Entity\Entity\EntityFormMode']));

  override(\Drupal\Core\Entity\Entity\EntityFormDisplay::loadMultiple(), map(['' => '\Drupal\Core\Entity\Entity\EntityFormDisplay[]']));
  override(\Drupal\Core\Entity\Entity\EntityFormDisplay::load(), map(['' => '\Drupal\Core\Entity\Entity\EntityFormDisplay']));
  override(\Drupal\Core\Entity\Entity\EntityFormDisplay::create(), map(['' => '\Drupal\Core\Entity\Entity\EntityFormDisplay']));

  expectedReturnValues(
    \Drupal\Core\Entity\EntityInterface::save(),
    \SAVED_NEW,
    \SAVED_UPDATED
  );

  expectedArguments(
    \Drupal\Core\Entity\EntityViewBuilderInterface::view(),
    2,
    \Drupal\Core\Language\LanguageInterface::LANGCODE_NOT_SPECIFIED,
    \Drupal\Core\Language\LanguageInterface::LANGCODE_NOT_APPLICABLE,
    \Drupal\Core\Language\LanguageInterface::LANGCODE_DEFAULT,
    \Drupal\Core\Language\LanguageInterface::LANGCODE_SITE_DEFAULT
  );

  expectedArguments(
    \Drupal\Core\Messenger\MessengerInterface::addMessage(),
    1,
    \Drupal\Core\Messenger\MessengerInterface::TYPE_STATUS,
    \Drupal\Core\Messenger\MessengerInterface::TYPE_WARNING,
    \Drupal\Core\Messenger\MessengerInterface::TYPE_ERROR
  );

}